# services.yaml
- System Management:
    - Homepage:
        icon: homepage.png
        href: http://localhost:8085
        description: "Local Homelab Landing Page"
    - Portainer:
        icon: portainer.png
        href: http://localhost:9000
        description: "Docker Container Management"
    - Uptime Kuma:
        icon: uptime-kuma.png
        href: http://localhost:3001
        description: "Local Services Monitoring"
    - Splunk:
        icon: splunk.png
        href: http://localhost:8000
        description: "Security Event & Log SIEM"
